"""AI-assisted Git hooks (Module 2 - Version Control).

  python ai/commit_assist.py scan          # pre-commit: block commits containing secrets
  python ai/commit_assist.py msg <file>    # prepare-commit-msg: write a Conventional Commit message

Secret scanning uses BOTH a regex baseline and the local LLM, so the benchmark can
compare them (bench/secret_scan_bench.py).
"""
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ollama_client import AI_ENABLED, OllamaError, ask  # noqa: E402

MAX_DIFF_LINES = 200

# ---- "Before AI" baseline: the kind of regex rules a typical hook would use ----
REGEX_RULES = [
    ("AWS access key", re.compile(r"AKIA[0-9A-Z]{16}")),
    ("GitHub token", re.compile(r"gh[pousr]_[A-Za-z0-9]{36}")),
    ("Private key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("Credential assignment",
     re.compile(r"(?i)(password|passwd|secret|api_?key|token)\w*[\"']?\s*[:=]")),
]


def regex_scan(diff):
    added = [ln[1:] for ln in diff.splitlines() if ln.startswith("+") and not ln.startswith("+++")]
    hits = []
    for line in added:
        for name, rx in REGEX_RULES:
            if rx.search(line):
                hits.append(f"{name}: {line.strip()[:80]}")
    return hits


SCAN_SYSTEM = (
    "You are a security reviewer checking a git diff before commit. A problem is a REAL "
    "hardcoded credential: API keys, tokens, passwords, private keys, webhook URLs with "
    "secrets, or connection strings containing a password. Reading a secret from an "
    "environment variable, a password input field, or a variable merely NAMED token/password "
    "is NOT a leak."
)

SCAN_PROMPT = """Diff (only lines starting with + are being added):

{diff}

First line must be exactly 'SECRET: yes' or 'SECRET: no'.
Second line: 'REASON: <short reason, name the variable if yes>'."""


def ai_scan(diff):
    r = ask(SCAN_PROMPT.format(diff=diff), system=SCAN_SYSTEM, temperature=0)
    first = r["text"].strip().splitlines()[0].lower() if r["text"].strip() else ""
    r["is_secret"] = "yes" in first
    return r


MSG_SYSTEM = "You write git commit messages in the Conventional Commits format."
MSG_PROMPT = """Write a commit message for this staged diff.

{diff}

Rules: first line '<type>(<scope>): <summary>' under 72 chars, type is one of
feat, fix, docs, test, refactor, chore, ci, build, perf. Then a blank line and
1-3 bullet points on what changed and why. Output only the message, no code fences."""


def ai_commit_message(diff):
    r = ask(MSG_PROMPT.format(diff=diff), system=MSG_SYSTEM, temperature=0.2)
    r["text"] = r["text"].strip().strip("`").strip()
    return r


def staged_diff():
    out = subprocess.run(["git", "diff", "--cached"], capture_output=True, text=True)
    lines = out.stdout.splitlines()
    return "\n".join(lines[:MAX_DIFF_LINES])


def cmd_scan():
    diff = staged_diff()
    if not diff:
        return 0
    regex_hits = regex_scan(diff)
    ai = {"is_secret": False, "text": "", "latency_s": 0}
    if AI_ENABLED:
        try:
            ai = ai_scan(diff)
        except OllamaError as e:
            print(f"[AI] secret scan skipped: {e}")

    if regex_hits or ai["is_secret"]:
        print("\n[pre-commit] Possible secret in staged changes - commit BLOCKED")
        for h in regex_hits:
            print("  regex :", h)
        if ai["is_secret"]:
            print("  AI    :", ai["text"].replace("\n", " | "), f"({ai['latency_s']}s)")
        print("Remove the secret (use an environment variable) or bypass with: git commit --no-verify\n")
        return 1
    mode = f"regex + AI, {ai['latency_s']}s" if AI_ENABLED else "regex only, AI off"
    print(f"[pre-commit] No secrets found ({mode})")
    return 0


def cmd_msg(msg_file, source=""):
    # Respect messages the developer typed (git commit -m, merges, amends)
    if not AI_ENABLED or source in ("message", "merge", "squash", "commit"):
        return 0
    with open(msg_file, encoding="utf-8") as f:
        existing = f.read()
    if any(ln.strip() and not ln.startswith("#") for ln in existing.splitlines()):
        return 0
    diff = staged_diff()
    if not diff:
        return 0
    try:
        r = ai_commit_message(diff)
    except OllamaError as e:
        print(f"[AI] commit message skipped: {e}")
        return 0
    with open(msg_file, "w", encoding="utf-8") as f:
        f.write(r["text"] + "\n\n# AI-generated by local LLM (" + r["model"] + "). Edit freely.\n" + existing)
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(2)
    if sys.argv[1] == "scan":
        sys.exit(cmd_scan())
    if sys.argv[1] == "msg":
        sys.exit(cmd_msg(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else ""))
    print(__doc__)
    sys.exit(2)
