"""Ask the local LLM to optimise Dockerfile.naive -> writes Dockerfile.ai

    python ai/optimize_dockerfile.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ollama_client import ask, extract_code_block  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROMPT = """Optimise this Dockerfile for a small Python Flask app.

Current Dockerfile:
```dockerfile
{dockerfile}
```

requirements.txt:
```
{requirements}
```

The app is a single file app.py started with `python app.py` on port 5000.
Goals: much smaller image, faster rebuilds when only app.py changes (layer caching),
run as a non-root user, no pip cache. Keep it a single working Dockerfile.

Reply with the full Dockerfile in one ```dockerfile code block, then a line
'CHANGES:' followed by one bullet per optimisation and why it helps."""


def main():
    with open(os.path.join(ROOT, "Dockerfile.naive")) as f:
        naive = f.read()
    with open(os.path.join(ROOT, "requirements.txt")) as f:
        reqs = f.read()

    print("Asking local LLM to optimise Dockerfile.naive ...")
    r = ask(PROMPT.format(dockerfile=naive, requirements=reqs), temperature=0.1)
    dockerfile = extract_code_block(r["text"])
    out = os.path.join(ROOT, "Dockerfile.ai")
    with open(out, "w") as f:
        f.write("# Generated by local LLM (" + r["model"] + ") from Dockerfile.naive\n" + dockerfile)

    changes = r["text"].split("CHANGES:", 1)[1].strip() if "CHANGES:" in r["text"] else "(model did not list changes)"
    os.makedirs(os.path.join(ROOT, "results", "after"), exist_ok=True)
    with open(os.path.join(ROOT, "results", "after", "dockerfile_ai_changes.md"), "w") as f:
        f.write(f"# AI Dockerfile optimisation ({r['model']}, {r['latency_s']}s)\n\n")
        f.write("```dockerfile\n" + dockerfile + "```\n\n## Changes the AI made\n\n" + changes + "\n")

    print(open(out).read())
    print("CHANGES:\n" + changes)
    print(f"\nSaved Dockerfile.ai  ({r['latency_s']}s). Review it, then run bench/docker_bench.py")


if __name__ == "__main__":
    main()
